trainer: generic
output_dir: results/alexnet

data_config:
    name: random
    n_train: 32768
    n_valid: 32768
    input_shape: [3, 224, 224]
    n_classes: 1000
    batch_size: 128
    use_dist_sampler_train: false
    use_dist_sampler_valid: false

model_config:
    model_type: alexnet
    num_classes: 1000
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 4
