trainer: generic
output_dir: results/cnn3d

data_config:
    name: dummy
    n_train: 8192
    n_valid: 8192
    input_shape: [1, 64, 64, 64]
    n_classes: 4
    batch_size: 128
    use_dist_sampler_train: false
    use_dist_sampler_valid: false

model_config:
    model_type: cnn3d
    input_shape: [1, 64, 64, 64]
    output_size: 4
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 4
