trainer: generic
output_dir: results/lstm

data_config:
    name: random
    n_train: 131072
    n_valid: 131072
    input_shape: [64, 512] # (seq_len, input_size)
    n_classes: 4
    batch_size: 128
    use_dist_sampler_train: false
    use_dist_sampler_valid: false

model_config:
    model_type: lstm
    input_size: 512
    hidden_size: 512
    output_size: 8
    n_lstm_layers: 4
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 4
